{"name": "test_fail", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "def test_fail():\n>       assert 0\nE       assert 0\n\ntest.py:15: AssertionError"}, "start": 1702571584308, "stop": 1702571584308, "uuid": "4cb423e6-a63d-41c8-ad48-58c3b76b27bf", "historyId": "c3e28e95d5b1558d519fcde9e05fbd6f", "testCaseId": "c3e28e95d5b1558d519fcde9e05fbd6f", "fullName": "test#test_fail", "labels": [{"name": "suite", "value": "test"}, {"name": "host", "value": "byemen"}, {"name": "thread", "value": "33587-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test"}]}